src/Pages/ContactDirectory/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServerWizardExample.Contacts;

namespace ServerWizardExample.Pages.ContactDirectory
{
    public class Index : PageModel
    {
        private readonly ContactService _service;
        public IList<Contact> Contacts { get; set; }

        public void OnGet()
        {
            Contacts = _service.All();
        }

        public Index(ContactService service)
        {
            _service = service;
        }
    }
}

src/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ServerWizardExample.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ServerWizardExample.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

src/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ServerWizardExample.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

src/Pages/Wizard/ContactInformationStep.cshtml.cs
namespace ServerWizardExample.Pages.Wizard
{
    public class ContactInformationStep : StepViewModel
    {
        public string Email { get; set; }
        public string Phone { get; set; }

        public ContactInformationStep()
        {
            Position = 1;
        }
    }
}

src/Pages/Wizard/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using ServerWizardExample.Contacts;

namespace ServerWizardExample.Pages.Wizard
{
    public class Index : PageModel
    {
        // Regarding cleaning the ModelState:
        // https://stackoverflow.com/questions/54356921/razor-views-bounded-property-not-updating-after-post

        [BindRequired]
        [BindProperty(SupportsGet = true)]
        public int CurrentStepIndex { get; set; }

        public IList<StepViewModel> Steps { get; set; }
        
        private readonly ContactService _service;

        public Index(ContactService service)
        {
            _service = service;
            InitializeSteps();
        }

        private void InitializeSteps()
        {
            Steps = typeof(StepViewModel)
                .Assembly
                .GetTypes()
                .Where(t => !t.IsAbstract && typeof(StepViewModel).IsAssignableFrom(t))
                .Select(t => (StepViewModel) Activator.CreateInstance(t))
                .OrderBy(x => x.Position)
                .ToList();
        }

        public IActionResult OnGetAsync(int? id)
        {
            if (id != null)
            {
                var client = _service.FindById((int) id);
                if (client != null)
                {
                    LoadWizardData(client);
                }
                else
                {
                    return NotFound();
                }
            }
            else
            {
                SetEmptyTempData();
            }

            return Page();

        }

        public PageResult OnPostNext(StepViewModel currentStep)
        {
            if (ModelState.IsValid) MoveToNextStep(currentStep);
            return Page();
        }

        public PageResult OnPostPrevious(StepViewModel currentStep)
        {
            if (ModelState.IsValid) MoveToPreviousStep(currentStep);
            return Page();
        }

        public IActionResult OnPostFinish(StepViewModel currentStep)
        {
            if (!ModelState.IsValid) return Page();

            var client = ProcessSteps(currentStep);
            _service.Save(client);
            return RedirectToPage("./../Index", new {id = client.Id});
        }

        private void LoadWizardData(Contact client)
        {
            TempData["ClientId"] = client.Id;
            
            Steps = StepMapper.ToSteps(client).OrderBy(x => x.Position).ToList();
            
            for (var i = 0; i < Steps.Count; i++)
            {
                TempData.Set($"Step{i}", Steps[i]);
            }
        }

        private void SetEmptyTempData()
        {
            TempData.Remove("ClientId");
            for (var i = 0; i < Steps.Count; i++)
            {
                TempData.Set($"Step{i}", Steps[i]);
            }
        }

        private void MoveToNextStep(StepViewModel currentStep) => JumpToStep(currentStep, CurrentStepIndex + 1);

        private void MoveToPreviousStep(StepViewModel currentStep) => JumpToStep(currentStep, CurrentStepIndex - 1);

        private void JumpToStep(StepViewModel currentStep, int nextStepPosition)
        {
            TempData.Set($"Step{CurrentStepIndex}", currentStep);
            CurrentStepIndex = nextStepPosition;
            JsonConvert.PopulateObject((string) TempData.Peek($"Step{CurrentStepIndex}"), Steps[CurrentStepIndex]);
            ModelState.Clear();
        }

        private Contact ProcessSteps(StepViewModel finalStep)
        {
            for (var i = 0; i < Steps.Count; i++)
            {
                var data = TempData.Peek($"Step{i}");
                JsonConvert.PopulateObject((string) data, Steps[i]);
            }

            Steps[CurrentStepIndex] = finalStep;

            var contact = new Contact();
            if (TempData.Peek("ClientId") != null)
            {
                contact.Id = (int) TempData["ClientId"];
            }
    
            StepMapper.EnrichClient(contact, Steps);
            return contact;
        }
    }
}

src/Pages/Wizard/PersonalInformationStep.cshtml.cs
namespace ServerWizardExample.Pages.Wizard
{
    public class PersonalInformationStep : StepViewModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public PersonalInformationStep()
        {
            Position = 0;
        }
    }
}

src/Pages/ContactDirectory/Index.cshtml
@page
@model ServerWizardExample.Pages.ContactDirectory.Index

@{
    ViewData["Title"] = "Contacts";
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<table class="table">
    <thead>
    <tr>
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Email
        </th>
        <th>
           Phone 
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Contacts)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
        </tr>
    }
    </tbody>
</table>
</body>
</html>

src/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p><a asp-page="./Wizard/Index">Open the wizard</a></p>
    <p><a asp-page="./ContactDirectory/Index">Open contacts directory</a></p>
</div>

src/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ServerWizardExample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ServerWizardExample</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ServerWizardExample - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

src/Pages/Wizard/ContactInformationStep.cshtml
@model ContactInformationStep

<div>
    <div asp-validation-summary="None" class="text-danger"></div>

    <div class="row my-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Contact Information</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="Email" class="control-label required"></label>
                                <input asp-for="Email" class="form-control cleave-ssn"/>
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="Phone" class="control-label"></label>
                                <input asp-for="Phone" class="form-control"/>
                                <span asp-validation-for="Phone" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/Pages/Wizard/Index.cshtml
@page
@model ServerWizardExample.Pages.Wizard.Index

@{
    ViewData["Title"] = "New";
    var currentStep = Model.Steps[Model.CurrentStepIndex];
    var viewName = currentStep.ToString().Substring(currentStep.ToString().LastIndexOf('.') + 1);
}


@using (Html.BeginForm())
{
    @Html.Hidden("StepType", Model.Steps[Model.CurrentStepIndex].GetType())
    @Html.HiddenFor(m => m.CurrentStepIndex, Model.CurrentStepIndex)
    @await Html.PartialAsync(viewName, currentStep)

    if (Model.CurrentStepIndex > 0)
    {
        <input type="submit" value="Previous" name="prev" asp-page-handler="Previous" class="btn btn-secondary"/>
    }

    if (Model.CurrentStepIndex < (Model.Steps.Count - 1))
    {
        <input type="submit" value="Next" name="next" asp-page-handler="Next" class="btn btn-primary"/>
        <input type="submit" value="Save & Close" name="save" asp-page-handler="Finish" class="btn btn-primary float-right"/>
    }
    else
    {
        <input type="submit" value="Finish" name="finish" asp-page-handler="Finish" class="btn btn-primary"/>
    }
}

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

src/Pages/Wizard/PersonalInformationStep.cshtml
@model PersonalInformationStep

<div>
    <div asp-validation-summary="None" class="text-danger"></div>
    
    <div class="row my-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Personal Information</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="FirstName" class="control-label required"></label>
                                <input asp-for="FirstName" class="form-control cleave-ssn"/>
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="LastName" class="control-label"></label>
                                <input asp-for="LastName" class="form-control"/>
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>